### ISSUE TITLE
touch sensor not calibrated error, and birdie on 7.2mhz

### ISSUE THREAD

**Issue by brokechubb** [amunters/bitx40#14]
Hello, and thank you for the firmware.

My issue is that after i did the ptt sense mod whenever i start up the radio i am getting a "touch sensor" error. So far the only mods I have done are the ptt sense, 10T pot, removed C91 and C92, and the function button.

Also, do you have any insight on the 7.2mhz birdie? I recently transferred the radio to one of the metal cases from India from a 3d printed case and the birdie has gotten stronger, no matter what I set the lsb drive level to. Today I even changed the wiring from the radiunio to the dds pins to some shielded coax, rg-58 because that's what I had on hand. Now even though the radio sounds better overall with these changes, the birdie on 7.2 mhz is still very strong. Any ideas or is this something I can not avoid due to the mixing?

Thanks again.

Jimmy
K3CHB

**Comment by brokechubb** [comment]
The error says "touch sensors not detected"

**Comment by amunters** [comment]
Hi Jimmy,

The message "touch sensors not detected" is just a user notification, not an error.
At startup, the software checks whether or not the touch sensor mod is installed and enables/disables the related functions accordingly.

Regarding the 7.2 MHz birdie: do you also have it in USB mode? Probably not, because in USB mode the VFO operates on the high side of the IF (12+7=19 MHz instead of 12-7=5 MHz in LSB mode). Switching to v2 software would solve this issue, because it allows you to always use high side operation even in LSB mode.

Hope this helps.

73 Allard PE1NWL

**Comment by brokechubb** [comment]
Thanks alot!
